name: Python new CI

on:
  push:
    branches:
      - Master

  
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
         python-version: 3.12.0-alpha.7
         architecture: x64


      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with Pytest
        run: |
          pip3 install coverage
          pwd && ls -la
          python3 -m coverage run -m unittest src/main/python/helloworld.py
          python3 -m coverage report src/main/python/helloworld.py
          python3 -m coverage report
          python3 -m coverage html
          python3 -m coverage xml
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
